# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
"Hi there Sam!"

'Hi there Sam!'

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet = "Earth"
diameter = 12742

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

['hello']


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as pv
array=pv.zeros(10)

In [6]:
import numpy as pv
array=pv.ones(10)*5

## 5. Create an array of all the even integers from 20 to 35

In [7]:
import numpy as pv
array=pv.arange(20,35,2)


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
import numpy as pv
x=pv.arange(0,9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [10]:
a = pv.array([1, 2, 3])
b = pv.array([4, 5, 6])
x=pv.concatenate([a,b])
print(x)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [12]:
import pandas as pd

In [13]:
data = [['jaga', 20], ['bobby', 15], ['eswar', 85]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df

Name  Age
0   jaga   20
1  bobby   15
2  eswar   85

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [14]:
x=pd.date_range(start='1-1-2023',end='10-02-2023')
x

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [16]:
pv = pd.DataFrame(lists, columns =['s_no','Name', 'Age']) 
pv

s_no Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24